// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/tax/v1beta1/tax.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the set of params for the tax module.
type Params struct {
	Taxes []Tax `protobuf:"bytes,1,rep,name=taxes,proto3" json:"taxes" yaml:"taxes"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e026d951b912679, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTaxes() []Tax {
	if m != nil {
		return m.Taxes
	}
	return nil
}

// Tax defines
type Tax struct {
	// name defines the name of the tax
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
	// rate specifies the distributing amount by ratio of total tax source
	Rate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=rate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"rate" yaml:"rate"`
	// collection_address defines the bech32-encoded address of the tax pool to distribute
	CollectionAddress string `protobuf:"bytes,3,opt,name=collection_address,json=collectionAddress,proto3" json:"collection_address,omitempty" yaml:"collection_address"`
	// collection_account_name defines the bech32-encoded address of the tax pool to distribute
	CollectionAccountName string `protobuf:"bytes,4,opt,name=collection_account_name,json=collectionAccountName,proto3" json:"collection_account_name,omitempty" yaml:"collection_account_name"`
	// tax_source_address defines the bech32-encoded address that source of the tax
	TaxSourceAddress string `protobuf:"bytes,5,opt,name=tax_source_address,json=taxSourceAddress,proto3" json:"tax_source_address,omitempty" yaml:"tax_source_address"`
	// tax_source_account_name defines the bech32-encoded address that source of the tax
	TaxSourceAccountName string `protobuf:"bytes,6,opt,name=tax_source_account_name,json=taxSourceAccountName,proto3" json:"tax_source_account_name,omitempty" yaml:"tax_source_account_name"`
	// start_time specifies the start time of the tax
	StartTime time.Time `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	// end_time specifies the end time of the tax
	EndTime time.Time `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
}

func (m *Tax) Reset()      { *m = Tax{} }
func (*Tax) ProtoMessage() {}
func (*Tax) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e026d951b912679, []int{1}
}
func (m *Tax) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tax) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tax.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tax) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tax.Merge(m, src)
}
func (m *Tax) XXX_Size() int {
	return m.Size()
}
func (m *Tax) XXX_DiscardUnknown() {
	xxx_messageInfo_Tax.DiscardUnknown(m)
}

var xxx_messageInfo_Tax proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.tax.v1beta1.Params")
	proto.RegisterType((*Tax)(nil), "cosmos.tax.v1beta1.Tax")
}

func init() { proto.RegisterFile("tendermint/tax/v1beta1/tax.proto", fileDescriptor_3e026d951b912679) }

var fileDescriptor_3e026d951b912679 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xbf, 0x6f, 0xd3, 0x40,
	0x18, 0xf5, 0x91, 0x1f, 0x4d, 0x2f, 0x48, 0xa5, 0x56, 0x50, 0xd2, 0xa0, 0xfa, 0xc2, 0x21, 0x50,
	0x06, 0xb0, 0xd5, 0xb2, 0x45, 0x42, 0x88, 0xc0, 0x56, 0x84, 0xc0, 0xcd, 0x80, 0x58, 0xa2, 0x8b,
	0x7d, 0x04, 0x8b, 0xd8, 0x17, 0xf9, 0x2e, 0xc8, 0x59, 0x61, 0x61, 0xec, 0xc8, 0xd8, 0x3f, 0x27,
	0x63, 0x47, 0x04, 0x92, 0x41, 0xc9, 0xc6, 0x98, 0xbf, 0x00, 0xdd, 0x9d, 0xd3, 0x98, 0x86, 0xa8,
	0x8b, 0x7d, 0xf7, 0x7d, 0xef, 0xbd, 0xef, 0x7b, 0xd6, 0x33, 0x6c, 0x09, 0x1a, 0xf9, 0x34, 0x0e,
	0x83, 0x48, 0x38, 0x82, 0x24, 0xce, 0xa7, 0xa3, 0x01, 0x15, 0xe4, 0x48, 0x9e, 0xed, 0x71, 0xcc,
	0x04, 0x33, 0x4d, 0x8f, 0xf1, 0x90, 0x71, 0x5b, 0x56, 0xb2, 0x6e, 0xb3, 0x36, 0x64, 0x43, 0xa6,
	0xda, 0x8e, 0x3c, 0x69, 0x64, 0xf3, 0x40, 0x23, 0xfb, 0xba, 0x91, 0xd1, 0x74, 0xcb, 0xd2, 0x37,
	0x67, 0x40, 0x38, 0xbd, 0x9c, 0xe1, 0xb1, 0x20, 0xca, 0xfa, 0x68, 0xc8, 0xd8, 0x70, 0x44, 0x1d,
	0x75, 0x1b, 0x4c, 0xde, 0x3b, 0x22, 0x08, 0x29, 0x17, 0x24, 0x1c, 0x6b, 0x00, 0x3e, 0x85, 0xe5,
	0xd7, 0x24, 0x26, 0x21, 0x37, 0x9f, 0xc3, 0x92, 0x20, 0x09, 0xe5, 0x0d, 0xd0, 0x2a, 0xb4, 0xab,
	0xc7, 0x75, 0x7b, 0x73, 0x3f, 0xbb, 0x47, 0x92, 0x6e, 0x6d, 0x96, 0x22, 0x63, 0x99, 0xa2, 0x9b,
	0x53, 0x12, 0x8e, 0x3a, 0x58, 0x71, 0xb0, 0xab, 0xb9, 0x9d, 0xe2, 0xb7, 0x73, 0x64, 0xe0, 0x9f,
	0x25, 0x58, 0xe8, 0x91, 0xc4, 0xbc, 0x07, 0x8b, 0x11, 0x09, 0x69, 0x03, 0xb4, 0x40, 0x7b, 0xb7,
	0xbb, 0xb7, 0x4c, 0x51, 0x55, 0x93, 0x64, 0x15, 0xbb, 0xaa, 0x69, 0xbe, 0x81, 0xc5, 0x98, 0x08,
	0xda, 0xb8, 0xa1, 0x40, 0x4f, 0xa4, 0xfa, 0x8f, 0x14, 0x3d, 0x18, 0x06, 0xe2, 0xc3, 0x64, 0x60,
	0x7b, 0x2c, 0xcc, 0x1c, 0x67, 0xaf, 0x47, 0xdc, 0xff, 0xe8, 0x88, 0xe9, 0x98, 0x72, 0xfb, 0x05,
	0xf5, 0xd6, 0x92, 0x52, 0x03, 0xbb, 0x4a, 0xca, 0x7c, 0x09, 0x4d, 0x8f, 0x8d, 0x46, 0xd4, 0x13,
	0x01, 0x8b, 0xfa, 0xc4, 0xf7, 0x63, 0xca, 0x79, 0xa3, 0xa0, 0x06, 0x1c, 0x2e, 0x53, 0x74, 0xa0,
	0x29, 0x9b, 0x18, 0xec, 0xee, 0xaf, 0x8b, 0xcf, 0x74, 0xcd, 0xfc, 0x02, 0x60, 0x3d, 0x0f, 0xf5,
	0x3c, 0x36, 0x89, 0x44, 0x5f, 0x39, 0x2b, 0x2a, 0xcd, 0x93, 0x59, 0x8a, 0xc0, 0x9f, 0x14, 0xdd,
	0xdd, 0x02, 0x7b, 0xc8, 0xc2, 0x40, 0xd0, 0x70, 0x2c, 0xa6, 0xcb, 0x14, 0x59, 0x9b, 0xc3, 0x73,
	0x50, 0xec, 0xde, 0xce, 0x6d, 0xa0, 0x1b, 0xaf, 0xe4, 0x67, 0x3a, 0x81, 0xa6, 0x20, 0x49, 0x9f,
	0xb3, 0x49, 0xec, 0xd1, 0x4b, 0x4f, 0xa5, 0xab, 0x9e, 0x36, 0x31, 0xd8, 0xbd, 0x25, 0x48, 0x72,
	0xaa, 0x6a, 0x2b, 0x4b, 0x9f, 0x01, 0xac, 0xe7, 0x91, 0x79, 0x4b, 0xe5, 0x7f, 0x2d, 0x6d, 0x81,
	0xfd, 0xcf, 0xd2, 0x16, 0x28, 0x76, 0x6b, 0xeb, 0x05, 0x72, 0x8e, 0xde, 0x42, 0xc8, 0x05, 0x89,
	0x45, 0x5f, 0x66, 0xb2, 0xb1, 0xd3, 0x02, 0xed, 0xea, 0x71, 0xd3, 0xd6, 0x81, 0xb5, 0x57, 0x81,
	0xb5, 0x7b, 0xab, 0xc0, 0x76, 0x0f, 0xb3, 0xe0, 0xed, 0xeb, 0x69, 0x6b, 0x2e, 0x3e, 0xfb, 0x85,
	0x80, 0xbb, 0xab, 0x0a, 0x12, 0x6e, 0xba, 0xb0, 0x42, 0x23, 0x5f, 0xeb, 0x56, 0xae, 0xd5, 0xbd,
	0x93, 0xe9, 0xee, 0x69, 0xdd, 0x15, 0x53, 0xab, 0xee, 0xd0, 0xc8, 0x97, 0xd0, 0x4e, 0xe5, 0xeb,
	0x39, 0x32, 0x64, 0xba, 0xbb, 0x4f, 0x67, 0x73, 0x0b, 0x5c, 0xcc, 0x2d, 0xf0, 0x7b, 0x6e, 0x81,
	0xb3, 0x85, 0x65, 0x5c, 0x2c, 0x2c, 0xe3, 0xfb, 0xc2, 0x32, 0xde, 0xdd, 0xcf, 0x85, 0xf6, 0xca,
	0xff, 0x9f, 0xa8, 0xa7, 0xca, 0xed, 0xa0, 0xac, 0x96, 0x78, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x67, 0x02, 0x98, 0x7f, 0x24, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Taxes) > 0 {
		for iNdEx := len(m.Taxes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Taxes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTax(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Tax) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tax) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tax) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTax(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x42
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTax(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x3a
	if len(m.TaxSourceAccountName) > 0 {
		i -= len(m.TaxSourceAccountName)
		copy(dAtA[i:], m.TaxSourceAccountName)
		i = encodeVarintTax(dAtA, i, uint64(len(m.TaxSourceAccountName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TaxSourceAddress) > 0 {
		i -= len(m.TaxSourceAddress)
		copy(dAtA[i:], m.TaxSourceAddress)
		i = encodeVarintTax(dAtA, i, uint64(len(m.TaxSourceAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CollectionAccountName) > 0 {
		i -= len(m.CollectionAccountName)
		copy(dAtA[i:], m.CollectionAccountName)
		i = encodeVarintTax(dAtA, i, uint64(len(m.CollectionAccountName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CollectionAddress) > 0 {
		i -= len(m.CollectionAddress)
		copy(dAtA[i:], m.CollectionAddress)
		i = encodeVarintTax(dAtA, i, uint64(len(m.CollectionAddress)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Rate.Size()
		i -= size
		if _, err := m.Rate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTax(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTax(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTax(dAtA []byte, offset int, v uint64) int {
	offset -= sovTax(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Taxes) > 0 {
		for _, e := range m.Taxes {
			l = e.Size()
			n += 1 + l + sovTax(uint64(l))
		}
	}
	return n
}

func (m *Tax) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTax(uint64(l))
	}
	l = m.Rate.Size()
	n += 1 + l + sovTax(uint64(l))
	l = len(m.CollectionAddress)
	if l > 0 {
		n += 1 + l + sovTax(uint64(l))
	}
	l = len(m.CollectionAccountName)
	if l > 0 {
		n += 1 + l + sovTax(uint64(l))
	}
	l = len(m.TaxSourceAddress)
	if l > 0 {
		n += 1 + l + sovTax(uint64(l))
	}
	l = len(m.TaxSourceAccountName)
	if l > 0 {
		n += 1 + l + sovTax(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovTax(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovTax(uint64(l))
	return n
}

func sovTax(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTax(x uint64) (n int) {
	return sovTax(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTax
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taxes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taxes = append(m.Taxes, Tax{})
			if err := m.Taxes[len(m.Taxes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTax(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTax
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Tax) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTax
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tax: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tax: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionAccountName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionAccountName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxSourceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaxSourceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxSourceAccountName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaxSourceAccountName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTax
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTax
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTax
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTax(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTax
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTax(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTax
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTax
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTax
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTax
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTax
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTax
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTax        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTax          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTax = fmt.Errorf("proto: unexpected end of group")
)
