// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/budget/v1beta1/budget.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the budget module.
type Params struct {
	// The universal epoch length in number of blocks
	// A collection of budgets is executed with this epoch_blocks parameter
	EpochBlocks uint32 `protobuf:"varint,1,opt,name=epoch_blocks,json=epochBlocks,proto3" json:"epoch_blocks,omitempty" yaml:"epoch_blocks"`
	// Budgets parameter can be added, modified, and deleted through
	// parameter change governance proposal
	Budgets []Budget `protobuf:"bytes,2,rep,name=budgets,proto3" json:"budgets" yaml:"budgets"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df5cca239dd8691, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEpochBlocks() uint32 {
	if m != nil {
		return m.EpochBlocks
	}
	return 0
}

func (m *Params) GetBudgets() []Budget {
	if m != nil {
		return m.Budgets
	}
	return nil
}

// Budget defines a budget object.
type Budget struct {
	// name defines the name of the budget
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
	// rate specifies the distributing amount by ratio of total budget source
	Rate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=rate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"rate" yaml:"rate"`
	// source_address defines the bech32-encoded address that source of the budget
	SourceAddress string `protobuf:"bytes,3,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty" yaml:"source_address"`
	// destination_address defines the bech32-encoded address of the budget pool to distribute
	DestinationAddress string `protobuf:"bytes,4,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty" yaml:"destination_address"`
	// start_time specifies the start time of the budget
	StartTime time.Time `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	// end_time specifies the end time of the budget
	EndTime time.Time `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
}

func (m *Budget) Reset()      { *m = Budget{} }
func (*Budget) ProtoMessage() {}
func (*Budget) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df5cca239dd8691, []int{1}
}
func (m *Budget) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Budget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Budget.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Budget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Budget.Merge(m, src)
}
func (m *Budget) XXX_Size() int {
	return m.Size()
}
func (m *Budget) XXX_DiscardUnknown() {
	xxx_messageInfo_Budget.DiscardUnknown(m)
}

var xxx_messageInfo_Budget proto.InternalMessageInfo

// TotalCollectedCoins defines total collected coins with relevant metadata.
type TotalCollectedCoins struct {
	// total_collected_coins specifies the total collected coins in a budget ever since the budget is created
	TotalCollectedCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=total_collected_coins,json=totalCollectedCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_collected_coins" yaml:"total_collected_coins"`
}

func (m *TotalCollectedCoins) Reset()         { *m = TotalCollectedCoins{} }
func (m *TotalCollectedCoins) String() string { return proto.CompactTextString(m) }
func (*TotalCollectedCoins) ProtoMessage()    {}
func (*TotalCollectedCoins) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df5cca239dd8691, []int{2}
}
func (m *TotalCollectedCoins) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TotalCollectedCoins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TotalCollectedCoins.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TotalCollectedCoins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalCollectedCoins.Merge(m, src)
}
func (m *TotalCollectedCoins) XXX_Size() int {
	return m.Size()
}
func (m *TotalCollectedCoins) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalCollectedCoins.DiscardUnknown(m)
}

var xxx_messageInfo_TotalCollectedCoins proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.budget.v1beta1.Params")
	proto.RegisterType((*Budget)(nil), "cosmos.budget.v1beta1.Budget")
	proto.RegisterType((*TotalCollectedCoins)(nil), "cosmos.budget.v1beta1.TotalCollectedCoins")
}

func init() {
	proto.RegisterFile("tendermint/budget/v1beta1/budget.proto", fileDescriptor_9df5cca239dd8691)
}

var fileDescriptor_9df5cca239dd8691 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xed, 0x36, 0xa4, 0xed, 0x86, 0xb6, 0xc2, 0xa1, 0x90, 0x06, 0xea, 0x8d, 0x16, 0xa9,
	0x8a, 0x84, 0xb0, 0xd5, 0x72, 0x8b, 0x84, 0x04, 0x2e, 0x9c, 0x5b, 0xac, 0x1e, 0x10, 0x17, 0x6b,
	0x6d, 0x2f, 0xae, 0x55, 0xdb, 0x1b, 0x79, 0x37, 0x88, 0xbe, 0x01, 0xc7, 0x1e, 0x91, 0x38, 0xd0,
	0x33, 0xef, 0xc0, 0xbd, 0x12, 0x97, 0x1e, 0x11, 0x07, 0x17, 0x25, 0x6f, 0x90, 0x27, 0x40, 0xfb,
	0xc7, 0x21, 0xa8, 0x91, 0xe0, 0x14, 0xcf, 0xcc, 0x37, 0xbf, 0x9d, 0xdd, 0xf9, 0x14, 0xb0, 0xcb,
	0x49, 0x11, 0x93, 0x32, 0x4f, 0x0b, 0xee, 0x86, 0xa3, 0x38, 0x21, 0xdc, 0x7d, 0xbf, 0x17, 0x12,
	0x8e, 0xf7, 0x74, 0xe8, 0x0c, 0x4b, 0xca, 0xa9, 0xb5, 0x15, 0x51, 0x96, 0x53, 0xe6, 0xe8, 0xa4,
	0xd6, 0x74, 0xef, 0x26, 0x34, 0xa1, 0x52, 0xe1, 0x8a, 0x2f, 0x25, 0xee, 0x6e, 0x2b, 0x71, 0xa0,
	0x0a, 0xba, 0x53, 0x95, 0x6c, 0x15, 0xb9, 0x21, 0x66, 0x64, 0x76, 0x52, 0x44, 0xd3, 0x42, 0xd7,
	0x61, 0x42, 0x69, 0x92, 0x11, 0x57, 0x46, 0xe1, 0xe8, 0x9d, 0xcb, 0xd3, 0x9c, 0x30, 0x8e, 0xf3,
	0xa1, 0x12, 0xa0, 0xcf, 0x26, 0x68, 0x1e, 0xe1, 0x12, 0xe7, 0xcc, 0x1a, 0x80, 0xdb, 0x64, 0x48,
	0xa3, 0x93, 0x20, 0xcc, 0x68, 0x74, 0xca, 0x3a, 0x66, 0xcf, 0xec, 0xaf, 0x7b, 0xf7, 0xa7, 0x15,
	0x6c, 0x9f, 0xe1, 0x3c, 0x1b, 0xa0, 0xf9, 0x2a, 0xf2, 0x5b, 0x32, 0xf4, 0x64, 0x64, 0x1d, 0x82,
	0x15, 0x75, 0x15, 0xd6, 0x59, 0xea, 0x2d, 0xf7, 0x5b, 0xfb, 0x3b, 0xce, 0xc2, 0x1b, 0x3a, 0x9e,
	0x0c, 0xbd, 0x7b, 0x97, 0x15, 0x34, 0xa6, 0x15, 0xdc, 0x50, 0x64, 0xdd, 0x8b, 0xfc, 0x9a, 0x32,
	0x68, 0x7c, 0xba, 0x80, 0x06, 0xfa, 0xbe, 0x0c, 0x9a, 0xaa, 0xc3, 0x7a, 0x04, 0x1a, 0x05, 0xce,
	0x89, 0x9c, 0x6a, 0xcd, 0xdb, 0x9c, 0x56, 0xb0, 0xa5, 0x7a, 0x45, 0x16, 0xf9, 0xb2, 0x68, 0xbd,
	0x06, 0x8d, 0x12, 0x73, 0xd2, 0x59, 0x92, 0xa2, 0x67, 0xe2, 0x90, 0x9f, 0x15, 0xdc, 0x4d, 0x52,
	0x7e, 0x32, 0x0a, 0x9d, 0x88, 0xe6, 0xfa, 0xf5, 0xf4, 0xcf, 0x13, 0x16, 0x9f, 0xba, 0xfc, 0x6c,
	0x48, 0x98, 0xf3, 0x92, 0x44, 0x7f, 0x90, 0x82, 0x81, 0x7c, 0x89, 0xb2, 0x9e, 0x83, 0x0d, 0x46,
	0x47, 0x65, 0x44, 0x02, 0x1c, 0xc7, 0x25, 0x61, 0xac, 0xb3, 0x2c, 0xe1, 0xdb, 0xd3, 0x0a, 0x6e,
	0x29, 0xf9, 0xdf, 0x75, 0xe4, 0xaf, 0xab, 0xc4, 0x0b, 0x15, 0x5b, 0x87, 0xa0, 0x1d, 0x13, 0xc6,
	0xd3, 0x02, 0xf3, 0x94, 0x16, 0x33, 0x4c, 0x43, 0x62, 0xec, 0x69, 0x05, 0xbb, 0x0a, 0xb3, 0x40,
	0x84, 0x7c, 0x6b, 0x2e, 0x5b, 0x03, 0xdf, 0x00, 0xc0, 0x38, 0x2e, 0x79, 0x20, 0x96, 0xd9, 0xb9,
	0xd5, 0x33, 0xfb, 0xad, 0xfd, 0xae, 0xa3, 0x36, 0xed, 0xd4, 0x9b, 0x76, 0x8e, 0xeb, 0x4d, 0x7b,
	0x3b, 0xfa, 0xb1, 0xef, 0xe8, 0x71, 0x67, 0xbd, 0xe8, 0xfc, 0x1a, 0x9a, 0xfe, 0x9a, 0x4c, 0x08,
	0xb9, 0xe5, 0x83, 0x55, 0x52, 0xc4, 0x8a, 0xdb, 0xfc, 0x27, 0xf7, 0x81, 0xe6, 0x6e, 0x6a, 0x7b,
	0xe8, 0x4e, 0x45, 0x5d, 0x21, 0x45, 0x2c, 0xa4, 0x83, 0xd5, 0x8f, 0x17, 0xd0, 0x90, 0xdb, 0xfc,
	0x66, 0x82, 0xf6, 0x31, 0xe5, 0x38, 0x3b, 0xa0, 0x59, 0x46, 0x22, 0x4e, 0xe2, 0x03, 0x9a, 0x16,
	0xcc, 0xfa, 0x62, 0x82, 0x2d, 0x2e, 0xf2, 0x41, 0x54, 0x17, 0x02, 0xe1, 0x61, 0x61, 0x41, 0xe1,
	0xa5, 0xed, 0x99, 0x97, 0x30, 0x23, 0x33, 0x27, 0x89, 0x5e, 0xef, 0x48, 0x8f, 0xf0, 0x50, 0x8d,
	0xb0, 0x90, 0x82, 0xbe, 0x5e, 0xc3, 0xfe, 0x7f, 0x58, 0x40, 0x0e, 0xe3, 0xb7, 0xf9, 0xcd, 0x09,
	0x07, 0x0d, 0x71, 0x07, 0xef, 0xd5, 0xe5, 0xd8, 0x36, 0xaf, 0xc6, 0xb6, 0xf9, 0x6b, 0x6c, 0x9b,
	0xe7, 0x13, 0xdb, 0xb8, 0x9a, 0xd8, 0xc6, 0x8f, 0x89, 0x6d, 0xbc, 0x7d, 0x3c, 0x87, 0xbf, 0xf9,
	0x0f, 0xf0, 0xa1, 0xfe, 0x90, 0xe7, 0x84, 0x4d, 0xf9, 0x94, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x17, 0x6a, 0x47, 0x71, 0x2c, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Budgets) > 0 {
		for iNdEx := len(m.Budgets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Budgets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBudget(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.EpochBlocks != 0 {
		i = encodeVarintBudget(dAtA, i, uint64(m.EpochBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Budget) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Budget) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Budget) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintBudget(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintBudget(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if len(m.DestinationAddress) > 0 {
		i -= len(m.DestinationAddress)
		copy(dAtA[i:], m.DestinationAddress)
		i = encodeVarintBudget(dAtA, i, uint64(len(m.DestinationAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SourceAddress) > 0 {
		i -= len(m.SourceAddress)
		copy(dAtA[i:], m.SourceAddress)
		i = encodeVarintBudget(dAtA, i, uint64(len(m.SourceAddress)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Rate.Size()
		i -= size
		if _, err := m.Rate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBudget(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintBudget(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TotalCollectedCoins) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TotalCollectedCoins) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TotalCollectedCoins) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalCollectedCoins) > 0 {
		for iNdEx := len(m.TotalCollectedCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalCollectedCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBudget(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintBudget(dAtA []byte, offset int, v uint64) int {
	offset -= sovBudget(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochBlocks != 0 {
		n += 1 + sovBudget(uint64(m.EpochBlocks))
	}
	if len(m.Budgets) > 0 {
		for _, e := range m.Budgets {
			l = e.Size()
			n += 1 + l + sovBudget(uint64(l))
		}
	}
	return n
}

func (m *Budget) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovBudget(uint64(l))
	}
	l = m.Rate.Size()
	n += 1 + l + sovBudget(uint64(l))
	l = len(m.SourceAddress)
	if l > 0 {
		n += 1 + l + sovBudget(uint64(l))
	}
	l = len(m.DestinationAddress)
	if l > 0 {
		n += 1 + l + sovBudget(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovBudget(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovBudget(uint64(l))
	return n
}

func (m *TotalCollectedCoins) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TotalCollectedCoins) > 0 {
		for _, e := range m.TotalCollectedCoins {
			l = e.Size()
			n += 1 + l + sovBudget(uint64(l))
		}
	}
	return n
}

func sovBudget(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBudget(x uint64) (n int) {
	return sovBudget(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBudget
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochBlocks", wireType)
			}
			m.EpochBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochBlocks |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budgets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Budgets = append(m.Budgets, Budget{})
			if err := m.Budgets[len(m.Budgets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBudget(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBudget
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Budget) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBudget
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Budget: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Budget: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBudget(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBudget
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TotalCollectedCoins) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBudget
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TotalCollectedCoins: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TotalCollectedCoins: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCollectedCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBudget
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBudget
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalCollectedCoins = append(m.TotalCollectedCoins, types.Coin{})
			if err := m.TotalCollectedCoins[len(m.TotalCollectedCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBudget(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBudget
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBudget(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBudget
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBudget
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBudget
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBudget
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBudget
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBudget        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBudget          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBudget = fmt.Errorf("proto: unexpected end of group")
)
