// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/budget/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60151551cef977ce, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60151551cef977ce, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryBudgetsRequest is the request type for the Query/Budgets RPC method.
type QueryBudgetsRequest struct {
	Name                string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BudgetSourceAddress string `protobuf:"bytes,2,opt,name=budget_source_address,json=budgetSourceAddress,proto3" json:"budget_source_address,omitempty"`
	CollectionAddress   string `protobuf:"bytes,3,opt,name=collection_address,json=collectionAddress,proto3" json:"collection_address,omitempty"`
}

func (m *QueryBudgetsRequest) Reset()         { *m = QueryBudgetsRequest{} }
func (m *QueryBudgetsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBudgetsRequest) ProtoMessage()    {}
func (*QueryBudgetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60151551cef977ce, []int{2}
}
func (m *QueryBudgetsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBudgetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBudgetsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBudgetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBudgetsRequest.Merge(m, src)
}
func (m *QueryBudgetsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBudgetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBudgetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBudgetsRequest proto.InternalMessageInfo

func (m *QueryBudgetsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryBudgetsRequest) GetBudgetSourceAddress() string {
	if m != nil {
		return m.BudgetSourceAddress
	}
	return ""
}

func (m *QueryBudgetsRequest) GetCollectionAddress() string {
	if m != nil {
		return m.CollectionAddress
	}
	return ""
}

// QueryBudgetsResponse is the response type for the Query/Budgets RPC method.
type QueryBudgetsResponse struct {
	Budgets []BudgetResponse `protobuf:"bytes,1,rep,name=budgets,proto3" json:"budgets"`
}

func (m *QueryBudgetsResponse) Reset()         { *m = QueryBudgetsResponse{} }
func (m *QueryBudgetsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBudgetsResponse) ProtoMessage()    {}
func (*QueryBudgetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60151551cef977ce, []int{3}
}
func (m *QueryBudgetsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBudgetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBudgetsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBudgetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBudgetsResponse.Merge(m, src)
}
func (m *QueryBudgetsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBudgetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBudgetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBudgetsResponse proto.InternalMessageInfo

func (m *QueryBudgetsResponse) GetBudgets() []BudgetResponse {
	if m != nil {
		return m.Budgets
	}
	return nil
}

type BudgetResponse struct {
	Budget              Budget                                   `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget"`
	TotalCollectedCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=total_collected_coins,json=totalCollectedCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_collected_coins" yaml:"total_collected_coins"`
}

func (m *BudgetResponse) Reset()         { *m = BudgetResponse{} }
func (m *BudgetResponse) String() string { return proto.CompactTextString(m) }
func (*BudgetResponse) ProtoMessage()    {}
func (*BudgetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60151551cef977ce, []int{4}
}
func (m *BudgetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BudgetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BudgetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BudgetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BudgetResponse.Merge(m, src)
}
func (m *BudgetResponse) XXX_Size() int {
	return m.Size()
}
func (m *BudgetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BudgetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BudgetResponse proto.InternalMessageInfo

func (m *BudgetResponse) GetBudget() Budget {
	if m != nil {
		return m.Budget
	}
	return Budget{}
}

func (m *BudgetResponse) GetTotalCollectedCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalCollectedCoins
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmos.budget.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmos.budget.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryBudgetsRequest)(nil), "cosmos.budget.v1beta1.QueryBudgetsRequest")
	proto.RegisterType((*QueryBudgetsResponse)(nil), "cosmos.budget.v1beta1.QueryBudgetsResponse")
	proto.RegisterType((*BudgetResponse)(nil), "cosmos.budget.v1beta1.BudgetResponse")
}

func init() {
	proto.RegisterFile("tendermint/budget/v1beta1/query.proto", fileDescriptor_60151551cef977ce)
}

var fileDescriptor_60151551cef977ce = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xb1, 0x6f, 0xd3, 0x4e,
	0x14, 0xce, 0xa5, 0xfd, 0xa5, 0xfa, 0x5d, 0x25, 0x24, 0x2e, 0x89, 0xd4, 0x46, 0xad, 0x53, 0x59,
	0x4a, 0x15, 0x5a, 0xd5, 0x56, 0xc3, 0x06, 0x13, 0xa9, 0xba, 0x17, 0xb3, 0x21, 0x21, 0xeb, 0x6c,
	0x1f, 0xc6, 0xc2, 0xbe, 0x73, 0x7d, 0x67, 0x44, 0x56, 0x06, 0x06, 0xc4, 0x80, 0xc4, 0x8c, 0xd8,
	0xf9, 0x4b, 0x3a, 0x56, 0x62, 0x61, 0x2a, 0x28, 0x61, 0x47, 0xe2, 0x2f, 0x40, 0xbe, 0x7b, 0x0e,
	0x0d, 0x6d, 0xa0, 0x53, 0x2e, 0xef, 0x7d, 0xdf, 0xe7, 0xef, 0x7d, 0xf7, 0x6c, 0x3c, 0x50, 0x8c,
	0x47, 0xac, 0xc8, 0x12, 0xae, 0xdc, 0xa0, 0x8c, 0x62, 0xa6, 0xdc, 0x17, 0x87, 0x01, 0x53, 0xf4,
	0xd0, 0x3d, 0x2d, 0x59, 0x31, 0x71, 0xf2, 0x42, 0x28, 0x41, 0xba, 0xa1, 0x90, 0x99, 0x90, 0x8e,
	0x81, 0x38, 0x00, 0xe9, 0xed, 0x2e, 0x67, 0x03, 0x52, 0xd3, 0x7b, 0x7b, 0x86, 0xee, 0x06, 0x54,
	0x32, 0xa3, 0x3b, 0xc7, 0xe5, 0x34, 0x4e, 0x38, 0x55, 0x89, 0xe0, 0x80, 0xed, 0xc4, 0x22, 0x16,
	0xfa, 0xe8, 0x56, 0x27, 0xa8, 0x6e, 0xc6, 0x42, 0xc4, 0x29, 0x73, 0xf5, 0xbf, 0xa0, 0x7c, 0xea,
	0x52, 0x0e, 0xde, 0x7a, 0x5b, 0xd0, 0xa2, 0x79, 0xe2, 0x52, 0xce, 0x85, 0xd2, 0x6a, 0xb2, 0x26,
	0x9a, 0x47, 0xfb, 0x46, 0x11, 0xc6, 0x30, 0x2d, 0xeb, 0xb2, 0xab, 0xda, 0x4f, 0x28, 0x12, 0x70,
	0x62, 0x77, 0x30, 0x79, 0x58, 0x79, 0x3d, 0xa1, 0x05, 0xcd, 0xa4, 0xc7, 0x4e, 0x4b, 0x26, 0x95,
	0xed, 0xe1, 0xf6, 0x42, 0x55, 0xe6, 0x82, 0x4b, 0x46, 0xee, 0xe3, 0x56, 0xae, 0x2b, 0x1b, 0x68,
	0x07, 0x0d, 0xd7, 0x47, 0xdb, 0xce, 0xb5, 0x91, 0x39, 0x86, 0x36, 0x5e, 0x3d, 0xbb, 0xe8, 0x37,
	0x3c, 0xa0, 0xd8, 0x6f, 0x11, 0x88, 0x8e, 0x35, 0xb8, 0x7e, 0x16, 0x21, 0x78, 0x95, 0xd3, 0x8c,
	0x69, 0xc9, 0xff, 0x3d, 0x7d, 0x26, 0x23, 0xdc, 0x35, 0x92, 0xbe, 0x14, 0x65, 0x11, 0x32, 0x9f,
	0x46, 0x51, 0xc1, 0xa4, 0xdc, 0x68, 0x6a, 0x50, 0xdb, 0x34, 0x1f, 0xe9, 0xde, 0x03, 0xd3, 0x22,
	0x07, 0x98, 0x84, 0x22, 0x4d, 0x59, 0x58, 0x25, 0x33, 0x27, 0xac, 0x68, 0xc2, 0xed, 0xdf, 0x1d,
	0x80, 0xdb, 0x4f, 0x70, 0x67, 0xd1, 0x0d, 0xcc, 0x78, 0x8c, 0xd7, 0x8c, 0x7a, 0x35, 0xe4, 0xca,
	0x70, 0x7d, 0x34, 0x58, 0x32, 0xa4, 0x21, 0xd6, 0x3c, 0x18, 0xb6, 0xe6, 0xda, 0x3f, 0x10, 0xbe,
	0xb5, 0x88, 0xa8, 0xd2, 0x33, 0xdd, 0x7f, 0xa4, 0x67, 0x68, 0x75, 0x7a, 0xa6, 0x49, 0x3e, 0x22,
	0xdc, 0x55, 0x42, 0xd1, 0xd4, 0x87, 0x51, 0x58, 0xe4, 0x57, 0xd7, 0x58, 0x45, 0x52, 0xb9, 0xdc,
	0x9c, 0x8b, 0x51, 0xc9, 0xe6, 0x52, 0x47, 0x22, 0xe1, 0xe3, 0x93, 0x4a, 0xe8, 0xe7, 0x45, 0x7f,
	0x6b, 0x42, 0xb3, 0xf4, 0x9e, 0x7d, 0xad, 0x8a, 0xfd, 0xe9, 0x6b, 0x7f, 0x18, 0x27, 0xea, 0x59,
	0x19, 0x38, 0xa1, 0xc8, 0x60, 0x87, 0xe0, 0xe7, 0x40, 0x46, 0xcf, 0x5d, 0x35, 0xc9, 0x99, 0xd4,
	0x82, 0xd2, 0x6b, 0x6b, 0x8d, 0xa3, 0x5a, 0x42, 0x17, 0x47, 0x1f, 0x9a, 0xf8, 0x3f, 0x9d, 0x28,
	0x79, 0x8d, 0x70, 0xcb, 0xac, 0x00, 0xb9, 0xb3, 0x64, 0xc6, 0xab, 0x3b, 0xd7, 0xdb, 0xbb, 0x09,
	0xd4, 0x44, 0x69, 0x0f, 0x5e, 0x7d, 0xfe, 0xfe, 0xbe, 0xd9, 0x27, 0xdb, 0xb5, 0xd1, 0x3f, 0x5e,
	0x4c, 0xb3, 0x72, 0xe4, 0x0d, 0xc2, 0x6b, 0x70, 0xbf, 0xe4, 0xaf, 0xf2, 0x8b, 0x2b, 0xd9, 0xdb,
	0xbf, 0x11, 0x16, 0xbc, 0xec, 0x6a, 0x2f, 0x3b, 0xc4, 0x5a, 0xe2, 0x05, 0x36, 0x62, 0x7c, 0x7c,
	0x36, 0xb5, 0xd0, 0xf9, 0xd4, 0x42, 0xdf, 0xa6, 0x16, 0x7a, 0x37, 0xb3, 0x1a, 0xe7, 0x33, 0xab,
	0xf1, 0x65, 0x66, 0x35, 0x1e, 0xef, 0x5f, 0x0a, 0xfe, 0xea, 0xc7, 0xe6, 0x65, 0x7d, 0xd0, 0x37,
	0x10, 0xb4, 0xf4, 0x7b, 0x7b, 0xf7, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x5b, 0xd9, 0xd8,
	0xd5, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns parameters of the budget module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Budgets returns all budgets.
	Budgets(ctx context.Context, in *QueryBudgetsRequest, opts ...grpc.CallOption) (*QueryBudgetsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.budget.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Budgets(ctx context.Context, in *QueryBudgetsRequest, opts ...grpc.CallOption) (*QueryBudgetsResponse, error) {
	out := new(QueryBudgetsResponse)
	err := c.cc.Invoke(ctx, "/cosmos.budget.v1beta1.Query/Budgets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns parameters of the budget module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Budgets returns all budgets.
	Budgets(context.Context, *QueryBudgetsRequest) (*QueryBudgetsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Budgets(ctx context.Context, req *QueryBudgetsRequest) (*QueryBudgetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Budgets not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.budget.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Budgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBudgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Budgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.budget.v1beta1.Query/Budgets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Budgets(ctx, req.(*QueryBudgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.budget.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Budgets",
			Handler:    _Query_Budgets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tendermint/budget/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBudgetsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBudgetsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBudgetsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CollectionAddress) > 0 {
		i -= len(m.CollectionAddress)
		copy(dAtA[i:], m.CollectionAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CollectionAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BudgetSourceAddress) > 0 {
		i -= len(m.BudgetSourceAddress)
		copy(dAtA[i:], m.BudgetSourceAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BudgetSourceAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBudgetsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBudgetsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBudgetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Budgets) > 0 {
		for iNdEx := len(m.Budgets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Budgets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BudgetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BudgetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BudgetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalCollectedCoins) > 0 {
		for iNdEx := len(m.TotalCollectedCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalCollectedCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Budget.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBudgetsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.BudgetSourceAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.CollectionAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBudgetsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Budgets) > 0 {
		for _, e := range m.Budgets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *BudgetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Budget.Size()
	n += 1 + l + sovQuery(uint64(l))
	if len(m.TotalCollectedCoins) > 0 {
		for _, e := range m.TotalCollectedCoins {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBudgetsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBudgetsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBudgetsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BudgetSourceAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BudgetSourceAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBudgetsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBudgetsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBudgetsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budgets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Budgets = append(m.Budgets, BudgetResponse{})
			if err := m.Budgets[len(m.Budgets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BudgetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BudgetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BudgetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budget", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Budget.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCollectedCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalCollectedCoins = append(m.TotalCollectedCoins, types.Coin{})
			if err := m.TotalCollectedCoins[len(m.TotalCollectedCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
